export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

export const EMPTY_USER = "EMPTY_USER";
export const EMPTY_ENVIRONMENT = "EMPTY_ENVIRONMENT";
export const EMPTY_EXECUTION_HISTORY = "EMPTY_EXECUTION_HISTORY";
export const EMPTY_OBJECT_BANK = "EMPTY_OBJECT_BANK";
export const EMPTY_PROJECT = "EMPTY_PROJECT";
export const EMPTY_REUSABLE_PROCESS = "EMPTY_REUSABLE_PROCESS";
export const EMPTY_TEAM = "EMPTY_TEAM";
export const EMPTY_ROLE = "EMPTY_ROLE";
export const EMPTY_TEST_CASE = "EMPTY_TEST_CASE";
export const COPY_TEST_CASE_PROCESS = 'COPY_TEST_CASE_PROCESS'

export const UPDATE_USER_DETAIL_REQUEST = "UPDATE_USER_DETAIL_REQUEST";
export const UPDATE_USER_DETAIL_SUCCESS = "UPDATE_USER_DETAIL_SUCCESS";
export const UPDATE_USER_DETAIL_FAILURE = "UPDATE_USER_DETAIL_FAILURE";

export const ROLE_REQUEST = "ROLE_REQUEST";
export const ROLE_SUCCESS = "ROLE_SUCCESS";
export const ROLE_FAILURE = "ROLE_FAILURE";

export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const EDIT_ROLE_SUCCESS = "EDIT_ROLE_SUCCESS";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const UPDATE_ROLE_PERMISSION_SUCCESS = "UPDATE_ROLE_PERMISSION_SUCCESS";

export const TEAM_REQUEST = "TEAM_REQUEST";
export const TEAM_FAILURE = "TEAM_FAILURE";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const ADD_TEAM_MEMBER_SUCCESS = "ADD_TEAM_MEMBER_SUCCESS";
export const REMOVE_TEAM_MEMBER_SUCCESS = "REMOVE_TEAM_MEMBER_SUCCESS";
export const TOGGLE_TEAM_USER_STATUS = "TOGGLE_TEAM_USER_STATUS";

export const PROJECT_REQUEST = "PROJECT_REQUEST";
export const PROJECT_FAILURE = "PROJECT_FAILURE";
export const GET_ALL_PROJECT_SUCCESS = "GET_ALL_PROJECT_SUCCESS";
export const GET_SELECTED_PROJECT = "GET_SELECTED_PROJECT";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const REMOVE_CURRENT_PROJECT_MEMBER = "REMOVE_CURRENT_PROJECT_MEMBER";
export const ADD_CURRENT_PROJECT_MEMBER = "ADD_CURRENT_PROJECT_MEMBER";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const EDIT_PROJECT_DETAILS = "EDIT_PROJECT_DETAILS";

export const TEST_CASE_REQUEST = "TEST_CASE_REQUEST";
export const TEST_CASE_FAILURE = "TEST_CASE_FAILURE";
export const GET_ALL_TEST_CASE = "GET_ALL_TEST_CASE";
export const CREATE_TEST_CASE = "CREATE_TEST_CASE";
export const UPDATE_CURRENT_TEST_CASE = "UPDATE_CURRENT_TEST_CASE";
export const DELETE_TEST_CASE = "DELETE_TEST_CASE";
export const GET_TEST_CASE_DETAILS_BY_ID = "GET_TEST_CASE_DETAILS_BY_ID";
export const GET_TEST_CASE_STEPS_BY_ID = "GET_TEST_CASE_STEPS_BY_ID";
export const GET_TEST_CASE_LOGS = "GET_TEST_CASE_LOGS";
export const GET_ACTION_EVENTS = "GET_ACTION_EVENTS";

//Process
export const ADD_PROCESS = "ADD_PROCESS";
export const EDIT_PROCESS = "EDIT_PROCESS";
export const DELETE_PROCESS = "DELETE_PROCESS";

//Step
export const ADD_STEP = "ADD_STEP";
export const EDIT_STEP = "EDIT_STEP";
export const DELETE_STEP = "DELETE_STEP";

export const REUSABLE_PROCESS_REQUEST = "REUSABLE_PROCESS_REQUEST";
export const REUSABLE_PROCESS_FAILURE = "REUSABLE_PROCESS_FAILURE";
export const GET_ALL_REUSABLE_PROCESS = "GET_ALL_REUSABLE_PROCESS";
export const CREATE_REUSABLE_PROCESS = "CREATE_REUSABLE_PROCESS";
export const UPDATE_CURRENT_REUSABLE_PROCESS =
  "UPDATE_CURRENT_REUSABLE_PROCESS";
export const DELETE_REUSABLE_PROCESS = "DELETE_REUSABLE_PROCESS";
export const GET_REUSABLE_PROCESS_DETAILS_BY_ID =
  "GET_REUSABLE_PROCESS_DETAILS_BY_ID";
export const GET_REUSABLE_PROCESS_STEPS_BY_ID =
  "GET_REUSABLE_PROCESS_STEPS_BY_ID";
export const DELETE_REUSABLE_STEP = "DELETE_REUSABLE_STEP";
export const ADD_REUSABLE_STEP = "ADD_REUSABLE_STEP";
export const EDIT_REUSABLE_STEP = "EDIT_REUSABLE_STEP";
export const GET_REUSABLE_PROCESS_LOGS = "GET_REUSABLE_PROCESS_LOGS";

export const OBJECT_BANK_REQUEST = "OBJECT_BANK_REQUEST";
export const OBJECT_BANK_FAILURE = "OBJECT_BANK_FAILURE";
export const GET_ALL_TEST_OBJECT = "GET_ALL_TEST_OBJECT";
export const GET_OBJECT_DETAILS_BY_ID = "GET_OBJECT_DETAILS_BY_ID";
export const CREATE_TEST_OBJECT = "CREATE_TEST_OBJECT";
export const UPDATE_TEST_OBJECT = "UPDATE_TEST_OBJECT";
export const DELETE_TEST_OBJECT = "DELETE_TEST_OBJECT";
export const ADD_OBJECT_LOCATOR = "ADD_OBJECT_LOCATOR";
export const GET_OBJECT_LOCATORS = "GET_OBJECT_LOCATORS";
export const DELETE_OBJECT_LOCATOR = "DELETE_OBJECT_LOCATOR";
export const GET_OBJECT_LOGS = "GET_OBJECT_LOGS";

export const EXECUTION_HISTORY_REQUEST = "EXECUTION_HISTORY_REQUEST";
export const EXECUTION_HISTORY_FAILURE = "EXECUTION_HISTORY_FAILURE";
export const GET_ALL_EXECUTION_HISTORY = "GET_ALL_EXECUTION_HISTORY";
export const DELETE_EXECUTION_HISTORY = "DELETE_EXECUTION_HISTORY";
export const GET_EXECUTION_HISTORY_BY_ID = "GET_EXECUTION_HISTORY_BY_ID";
export const DELETE_ALL_EXECUTION_HISTORY = "DELETE_ALL_EXECUTION_HISTORY";

export const ENVIRONMENT_REQUEST = "ENVIRONMENT_REQUEST";
export const ENVIRONMENT_FAILURE = "ENVIRONMENT_FAILURE";
export const GET_ALL_ENVIRONMENT = "GET_ALL_ENVIRONMENT";
export const DELETE_ENVIRONMENT = "DELETE_ENVIRONMENT";
export const ADD_ENVIRONMENT = "ADD_ENVIRONMENT";
export const ADD_COLUMN = "ADD_COLUMN";
export const UPDATE_COLUMN_VALUE = "UPDATE_COLUMN_VALUE";
export const DELETE_COLUMN = "DELETE_COLUMN";

//Machines
export const MACHINES_REQUEST = "MACHINES_REQUEST";
export const MACHINES_FAILURE = "MACHINES_FAILURE";
export const MACHINES_VERSION_CHECK = "MACHINES_VERSION_CHECK";
export const GET_ALL_MACHINES = "GET_ALL_MACHINES";
export const ADD_MACHINE = "ADD_MACHINE";
export const REMOVE_MACHINE = "REMOVE_MACHINE";


//Execution Suite
export const EXECUTION_SUITE_REQUEST = "EXECUTION_SUITE_REQUEST"
export const EXECUTION_SUITE_FAILURE = "EXECUTION_SUITE_FAILURE"
export const GET_ALL_EXECUTION_SUITE = "GET_ALL_EXECUTION_SUITE"
export const CREATE_EXECUTION_SUITE = "CREATE_EXECUTION_SUITE"
export const UPDATE_CURRENT_EXECUTION_SUITE = "UPDATE_CURRENT_EXECUTION_SUITE"
export const DELETE_EXECUTION_SUITE = "DELETE_EXECUTION_SUITE"
export const GET_EXECUTION_SUITE_DETAILS_BY_ID = "GET_EXECUTION_SUITE_DETAILS_BY_ID"
export const GET_EXECUTION_SUITE_TEST_CASE_BY_ID = "GET_EXECUTION_SUITE_TEST_CASE_BY_ID"
export const ADD_EXECUTION_SUITE_TEST_CASE = "ADD_EXECUTION_SUITE_TEST_CASE"
export const EDIT_EXECUTION_SUITE_TEST_CASE = "EDIT_EXECUTION_SUITE_TEST_CASE"
export const DELETE_EXECUTION_SUITE_TEST_CASE = "DELETE_EXECUTION_SUITE_TEST_CASE"
export const GET_EXECUTION_SUITE_LOGS = "GET_EXECUTION_SUITE_LOGS"
export const EMPTY_EXECUTION_SUITE = 'EMPTY_EXECUTION_SUITE'